// Mock dataset used ONLY when Supabase env vars are absent (pre-Phase-1 dev).
// Shapes match SCHEMA.md exactly so the UI swap to live data is a no-op.
// All names/addresses are fictional placeholders, not real RM117 jobs.

export const MOCK_JOBS = [
  {
    job_id: '26_001_Moreno',
    client_id: 'mock-client-1',
    referred_by_id: null,
    client_name: 'Carlos Moreno',
    address: '412 Maple Ave, Yonkers NY',
    phase: 'design_phase',
    phase_override: null,
    job_total: 18500,
    amount_billed: 9250,
    bill_flag: false,
    is_forefront: false,
    ff_commission: null,
    ff_commission_paid: null,
    notes: 'Two-story rear addition. Awaiting survey results before CD start.',
    last_correspondence: 'Sent revised floor plans for review',
    last_email_date: '2026-06-02T14:30:00Z',
    last_email_subject: 'Revised plans — second floor',
    import_notes: null,
    import_needs_review: false,
    created_at: '2026-01-12T10:00:00Z',
    updated_at: '2026-06-02T14:30:00Z',
  },
  {
    job_id: '26_004_FF_Delgado',
    client_id: 'mock-client-2',
    referred_by_id: 'mock-client-5',
    client_name: 'Delgado Properties LLC',
    address: '88 Warburton St, New Rochelle NY',
    phase: 'cd_phase',
    phase_override: null,
    job_total: 32000,
    amount_billed: 16000,
    bill_flag: true,
    is_forefront: true,
    ff_commission: 3200,
    ff_commission_paid: false,
    notes: 'Forefront referral. Gut renovation, 3 units.',
    last_correspondence: 'CD set 60% — structural review scheduled',
    last_email_date: '2026-06-05T09:15:00Z',
    last_email_subject: 'CD progress + structural',
    import_notes: null,
    import_needs_review: false,
    created_at: '2026-02-03T10:00:00Z',
    updated_at: '2026-06-05T09:15:00Z',
  },
  {
    job_id: '25_017_Okafor',
    client_id: 'mock-client-3',
    referred_by_id: null,
    client_name: 'Adaeze Okafor',
    address: '15 Crestwood Rd, Bronxville NY',
    phase: 'active',
    phase_override: null,
    job_total: 12000,
    amount_billed: 12000,
    bill_flag: false,
    is_forefront: false,
    ff_commission: null,
    ff_commission_paid: null,
    notes: 'Kitchen + bath interior reno. Final walkthrough pending.',
    last_correspondence: 'Punch list sent to contractor',
    last_email_date: '2026-05-28T16:00:00Z',
    last_email_subject: 'Punch list',
    import_notes: null,
    import_needs_review: false,
    created_at: '2025-09-20T10:00:00Z',
    updated_at: '2026-05-28T16:00:00Z',
  },
  {
    job_id: '26_009_Petrov',
    client_id: 'mock-client-4',
    referred_by_id: null,
    client_name: 'Mikhail Petrov',
    address: '230 Palmer Rd, Mount Vernon NY',
    phase: 'potential',
    phase_override: null,
    job_total: 0,
    amount_billed: 0,
    bill_flag: false,
    is_forefront: false,
    ff_commission: null,
    ff_commission_paid: null,
    notes: 'Initial consult done. Proposal to be drafted — new construction, two-family.',
    last_correspondence: 'Consult follow-up email sent',
    last_email_date: '2026-06-08T11:00:00Z',
    last_email_subject: 'Great meeting you — next steps',
    import_notes: null,
    import_needs_review: false,
    created_at: '2026-06-01T10:00:00Z',
    updated_at: '2026-06-08T11:00:00Z',
  },
  {
    job_id: '25_022_FF_Whitfield',
    client_id: 'mock-client-5',
    referred_by_id: null,
    client_name: 'Whitfield Holdings',
    address: '67 S 4th Ave, Mount Vernon NY',
    phase: 'on_hold',
    phase_override: null,
    job_total: 24500,
    amount_billed: 7350,
    bill_flag: false,
    is_forefront: true,
    ff_commission: 2450,
    ff_commission_paid: false,
    notes: 'On hold — client securing financing.',
    last_correspondence: 'Client asked to pause until Q3',
    last_email_date: '2026-04-14T13:45:00Z',
    last_email_subject: 'Pausing until financing closes',
    import_notes: null,
    import_needs_review: false,
    created_at: '2025-11-05T10:00:00Z',
    updated_at: '2026-04-14T13:45:00Z',
  },
  {
    job_id: '24_031_Lindqvist',
    client_id: 'mock-client-6',
    referred_by_id: null,
    client_name: 'Erik Lindqvist',
    address: '9 Hillside Terr, Tuckahoe NY',
    phase: 'completed',
    phase_override: null,
    job_total: 8500,
    amount_billed: 8500,
    bill_flag: false,
    is_forefront: false,
    ff_commission: null,
    ff_commission_paid: null,
    notes: 'Fire escape replacement. Closed out 2025.',
    last_correspondence: 'Final sign-off received',
    last_email_date: '2025-03-10T10:00:00Z',
    last_email_subject: 'Sign-off',
    import_notes: null,
    import_needs_review: false,
    created_at: '2024-10-15T10:00:00Z',
    updated_at: '2025-03-10T10:00:00Z',
  },
];

export const MOCK_PAYMENTS = [
  { id: 'mp-1', job_id: '26_001_Moreno', amount: 4625, payment_method: 'check', payment_type: 'retainer', paid_date: '2026-01-20', qbo_invoice_id: null, notes: null, created_at: '2026-01-20T10:00:00Z' },
  { id: 'mp-2', job_id: '26_001_Moreno', amount: 4625, payment_method: 'qb', payment_type: 'dp1', paid_date: '2026-03-15', qbo_invoice_id: 'QBO-1042', notes: null, created_at: '2026-03-15T10:00:00Z' },
  { id: 'mp-3', job_id: '26_004_FF_Delgado', amount: 8000, payment_method: 'check', payment_type: 'retainer', paid_date: '2026-02-10', qbo_invoice_id: null, notes: null, created_at: '2026-02-10T10:00:00Z' },
  { id: 'mp-4', job_id: '26_004_FF_Delgado', amount: 8000, payment_method: 'zelle', payment_type: 'dp1', paid_date: '2026-04-22', qbo_invoice_id: null, notes: null, created_at: '2026-04-22T10:00:00Z' },
  { id: 'mp-5', job_id: '25_017_Okafor', amount: 6000, payment_method: 'check', payment_type: 'retainer', paid_date: '2025-10-01', qbo_invoice_id: null, notes: null, created_at: '2025-10-01T10:00:00Z' },
  { id: 'mp-6', job_id: '25_017_Okafor', amount: 6000, payment_method: 'venmo', payment_type: 'final', paid_date: '2026-05-01', qbo_invoice_id: null, notes: null, created_at: '2026-05-01T10:00:00Z' },
  { id: 'mp-7', job_id: '25_022_FF_Whitfield', amount: 7350, payment_method: 'check', payment_type: 'retainer', paid_date: '2025-11-20', qbo_invoice_id: null, notes: null, created_at: '2025-11-20T10:00:00Z' },
  { id: 'mp-8', job_id: '24_031_Lindqvist', amount: 8500, payment_method: 'check', payment_type: 'final', paid_date: '2025-03-08', qbo_invoice_id: null, notes: null, created_at: '2025-03-08T10:00:00Z' },
];
